export interface Song {
  id: string;
  title: string;
  titleEn?: string;
  language: "zh" | "en" | "both";
  emoji: string;
  color: string;
  lyrics: string[];
  description: string;
}

export const SONGS_DATA: Song[] = [
  // 中文儿歌
  {
    id: "xiao-xing-xing",
    title: "小星星",
    titleEn: "Twinkle Twinkle Little Star",
    language: "both",
    emoji: "⭐",
    color: "#FFC107",
    lyrics: [
      "一闪一闪亮晶晶，",
      "满天都是小星星。",
      "挂在天上放光明，",
      "好像许多小眼睛。",
      "一闪一闪亮晶晶，",
      "满天都是小星星。",
    ],
    description: "最经典的儿歌，中英文都有",
  },
  {
    id: "liang-zhi-laohu",
    title: "两只老虎",
    language: "zh",
    emoji: "🐯",
    color: "#FF9800",
    lyrics: [
      "两只老虎，两只老虎，",
      "跑得快，跑得快。",
      "一只没有眼睛，",
      "一只没有尾巴，",
      "真奇怪，真奇怪。",
    ],
    description: "活泼有趣的经典儿歌",
  },
  {
    id: "xiao-tu-zi-guai-guai",
    title: "小兔子乖乖",
    language: "zh",
    emoji: "🐰",
    color: "#E91E63",
    lyrics: [
      "小兔子乖乖，把门儿开开。",
      "快点儿开开，我要进来。",
      "不开不开我不开，",
      "妈妈没回来，",
      "谁来也不开。",
    ],
    description: "教宝宝安全意识的儿歌",
  },
  {
    id: "xiao-mao-mi",
    title: "小花猫",
    language: "zh",
    emoji: "🐱",
    color: "#9C27B0",
    lyrics: [
      "小花猫，喵喵叫，",
      "看见老鼠就追跑。",
      "跑过来，跑过去，",
      "老鼠吓得到处跑。",
    ],
    description: "可爱的小花猫故事",
  },
  {
    id: "shi-shang-zhi-you",
    title: "世上只有妈妈好",
    language: "zh",
    emoji: "👩‍👧",
    color: "#F44336",
    lyrics: [
      "世上只有妈妈好，",
      "有妈的孩子像块宝。",
      "投进妈妈的怀抱，",
      "幸福享不了。",
    ],
    description: "温暖的亲情儿歌",
  },
  {
    id: "xiao-ya-zi",
    title: "数鸭子",
    language: "zh",
    emoji: "🦆",
    color: "#4CAF50",
    lyrics: [
      "门前大桥下，",
      "游过一群鸭。",
      "快来快来数一数，",
      "二四六七八。",
      "嘎嘎嘎嘎真呀真多呀，",
      "数不清到底多少鸭。",
    ],
    description: "学数数的经典儿歌",
  },
  {
    id: "xiao-luo-hao",
    title: "小螺号",
    language: "zh",
    emoji: "🐚",
    color: "#00BCD4",
    lyrics: [
      "小螺号，嘀嘀嘀吹，",
      "海鸥听了展翅飞。",
      "小螺号，嘀嘀嘀吹，",
      "浪花听了笑微微。",
    ],
    description: "海边的快乐儿歌",
  },
  // 英文儿歌
  {
    id: "old-macdonald",
    title: "Old MacDonald Had a Farm",
    language: "en",
    emoji: "🐄",
    color: "#8BC34A",
    lyrics: [
      "Old MacDonald had a farm,",
      "E-I-E-I-O!",
      "And on his farm he had a cow,",
      "E-I-E-I-O!",
      "With a moo-moo here,",
      "And a moo-moo there,",
      "Old MacDonald had a farm,",
      "E-I-E-I-O!",
    ],
    description: "Learn animal sounds!",
  },
  {
    id: "wheels-on-bus",
    title: "The Wheels on the Bus",
    language: "en",
    emoji: "🚌",
    color: "#FF5722",
    lyrics: [
      "The wheels on the bus",
      "go round and round,",
      "round and round,",
      "round and round.",
      "The wheels on the bus",
      "go round and round,",
      "all through the town!",
    ],
    description: "Fun bus ride song!",
  },
  {
    id: "head-shoulders",
    title: "Head, Shoulders, Knees and Toes",
    language: "en",
    emoji: "🧒",
    color: "#3F51B5",
    lyrics: [
      "Head, shoulders,",
      "knees and toes,",
      "knees and toes.",
      "Head, shoulders,",
      "knees and toes,",
      "knees and toes.",
      "Eyes and ears",
      "and mouth and nose.",
      "Head, shoulders,",
      "knees and toes,",
      "knees and toes!",
    ],
    description: "Learn body parts!",
  },
  {
    id: "baa-baa",
    title: "Baa Baa Black Sheep",
    language: "en",
    emoji: "🐑",
    color: "#607D8B",
    lyrics: [
      "Baa, baa, black sheep,",
      "have you any wool?",
      "Yes sir, yes sir,",
      "three bags full.",
      "One for the master,",
      "one for the dame,",
      "one for the little boy",
      "who lives down the lane.",
    ],
    description: "Classic nursery rhyme!",
  },
  {
    id: "itsy-bitsy",
    title: "Itsy Bitsy Spider",
    language: "en",
    emoji: "🕷️",
    color: "#795548",
    lyrics: [
      "The itsy bitsy spider",
      "went up the water spout.",
      "Down came the rain",
      "and washed the spider out.",
      "Out came the sun",
      "and dried up all the rain.",
      "And the itsy bitsy spider",
      "went up the spout again.",
    ],
    description: "A brave little spider!",
  },
];
